### ISSUE TITLE
gulp报错

### ISSUE THREAD

**Issue by hqm1988** [amazeui/react-starter-kit#11]
`SeedeMacBook-Pro:react-starter-kit hqm$ sudo gulp
[23:28:06] Failed to load external module babel-register
[23:28:06] Requiring external module babel-core/register
[23:28:07] Using gulpfile ~/workspace/AmazeUI/react-starter-kit/gulpfile.babel.js
[23:28:07] Starting 'build'...
[23:28:07] Starting 'clean'...
[23:28:07] Starting 'watch'...
2016-05-05 23:28 gulp[1826] (CarbonCore.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2016-05-05 23:28 gulp[1826] (CarbonCore.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2016-05-05 23:28 gulp[1826] (CarbonCore.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2016-05-05 23:28 gulp[1826] (CarbonCore.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2016-05-05 23:28 gulp[1826] (CarbonCore.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
[23:28:07] Finished 'watch' after 20 ms
2016-05-05 23:28 gulp[1826] (CarbonCore.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
[23:28:07] Finished 'clean' after 29 ms
[23:28:07] Starting 'styles'...
[23:28:07] Starting 'eslint'...
[23:28:07] Starting 'html'...
[23:28:07] Starting 'images'...
[23:28:08] Starting 'copy'...
[23:28:08] Starting 'browserify'...
2016-05-05 23:28 gulp[1826] (CarbonCore.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: watch null EMFILE
    at exports._errnoException (util.js:890:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1296:21)`

**Comment by minwe** [comment]
尝试重新安装 Node 4.x 版本，删除 `node_modules` 重新执行 `npm install`。

另外，执行 `gulp` 为什么要加 `sudo`？

**Comment by hqm1988** [comment]
换成Node v4.4.2可以了，谢谢！
之前生成新文件没有写入权限，所以加了sudo
