### ISSUE TITLE
 Error: watch ENOSPC

### ISSUE THREAD

**Issue by yinheli** [amazeui/react-starter-kit#3]
```bash

yinheli-dev ➜  kit git:(master) gulp dev           
[16:44:00] Using gulpfile /media/yinheli/data/develop/workspace/work/lab/react-hello-world/kit/gulpfile.js
[16:44:00] Starting 'default'...
[16:44:00] Starting 'clean'...
[16:44:00] Starting 'watch'...
[16:44:00] 'watch' errored after 10 ms
[16:44:00] Error: watch ENOSPC
    at exports._errnoException (util.js:746:11)
    at FSWatcher.start (fs.js:1172:11)
    at Object.fs.watch (fs.js:1198:11)
    at Gaze._watchDir (/media/yinheli/data/develop/workspace/work/lab/react-hello-world/kit/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:289:30)
    at /media/yinheli/data/develop/workspace/work/lab/react-hello-world/kit/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:358:10
    at iterate (/media/yinheli/data/develop/workspace/work/lab/react-hello-world/kit/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
    at Object.forEachSeries (/media/yinheli/data/develop/workspace/work/lab/react-hello-world/kit/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:66:3)
    at Gaze._initWatched (/media/yinheli/data/develop/workspace/work/lab/react-hello-world/kit/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:354:10)
    at Gaze.add (/media/yinheli/data/develop/workspace/work/lab/react-hello-world/kit/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:177:8)
    at new Gaze (/media/yinheli/data/develop/workspace/work/lab/react-hello-world/kit/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:74:10)
[16:44:00] 'default' errored after 18 ms
[16:44:00] Error: [object Object]
    at formatError (/home/yinheli/cnepay-develop/soft/node/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/home/yinheli/cnepay-develop/soft/node/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:129:20)
    at Gulp.Orchestrator._emitTaskDone (/media/yinheli/data/develop/workspace/work/lab/react-hello-world/kit/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /media/yinheli/data/develop/workspace/work/lab/react-hello-world/kit/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/media/yinheli/data/develop/workspace/work/lab/react-hello-world/kit/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/media/yinheli/data/develop/workspace/work/lab/react-hello-world/kit/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/media/yinheli/data/develop/workspace/work/lab/react-hello-world/kit/node_modules/run-sequence/index.js:53:5)
    at Gulp.onError (/media/yinheli/data/develop/workspace/work/lab/react-hello-world/kit/node_modules/run-sequence/index.js:60:4)
    at Gulp.emit (events.js:129:20)
[16:44:00] Finished 'clean' after 19 ms
yinheli-dev ➜  kit git:(master) node -v && npm -v && gulp -v
v0.12.4
2.10.1
[16:45:06] CLI version 3.9.0
[16:45:06] Local version 3.9.0


```

**Comment by yinheli** [comment]
已解决. 

ubuntu 执行
```bash
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```
